name: Deploy to Server

on:
  push:
    branches:
      - main # This triggers the action on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Specifies that the job runs on the latest Ubuntu runner provided by GitHub

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 # This action checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.UBUNTU_SERVER }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no gituser@139.177.197.79 'cd /srv/article_summarizer && git pull origin main'
